#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kdav
Version  : 20.04.1
Release  : 21
URL      : https://download.kde.org/stable/release-service/20.04.1/src/kdav-20.04.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/20.04.1/src/kdav-20.04.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/20.04.1/src/kdav-20.04.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: kdav-data = %{version}-%{release}
Requires: kdav-lib = %{version}-%{release}
Requires: kdav-license = %{version}-%{release}
Requires: kdav-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : qtbase-dev mesa-dev

%description
# KDAV
## What's this?
This is an DAV protocol implemention with KJobs.
Calendars and todos are supported, using either GroupDAV
or CalDAV, and contacts are supported using GroupDAV or
CardDAV.

%package data
Summary: data components for the kdav package.
Group: Data

%description data
data components for the kdav package.


%package dev
Summary: dev components for the kdav package.
Group: Development
Requires: kdav-lib = %{version}-%{release}
Requires: kdav-data = %{version}-%{release}
Provides: kdav-devel = %{version}-%{release}
Requires: kdav = %{version}-%{release}

%description dev
dev components for the kdav package.


%package lib
Summary: lib components for the kdav package.
Group: Libraries
Requires: kdav-data = %{version}-%{release}
Requires: kdav-license = %{version}-%{release}

%description lib
lib components for the kdav package.


%package license
Summary: license components for the kdav package.
Group: Default

%description license
license components for the kdav package.


%package locales
Summary: locales components for the kdav package.
Group: Default

%description locales
locales components for the kdav package.


%prep
%setup -q -n kdav-20.04.1
cd %{_builddir}/kdav-20.04.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589851496
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1589851496
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdav
cp %{_builddir}/kdav-20.04.1/COPYING %{buildroot}/usr/share/package-licenses/kdav/7e52b139aa82028afadf25f4b534d2404bf97cca
cp %{_builddir}/kdav-20.04.1/COPYING.LIB %{buildroot}/usr/share/package-licenses/kdav/ba8966e2473a9969bdcab3dc82274c817cfd98a1
pushd clr-build
%make_install
popd
%find_lang libkdav

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories5/kdav.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KDAV/DavCollection
/usr/include/KF5/KDAV/DavCollectionDeleteJob
/usr/include/KF5/KDAV/DavCollectionModifyJob
/usr/include/KF5/KDAV/DavCollectionsFetchJob
/usr/include/KF5/KDAV/DavCollectionsMultiFetchJob
/usr/include/KF5/KDAV/DavError
/usr/include/KF5/KDAV/DavItem
/usr/include/KF5/KDAV/DavItemCreateJob
/usr/include/KF5/KDAV/DavItemDeleteJob
/usr/include/KF5/KDAV/DavItemFetchJob
/usr/include/KF5/KDAV/DavItemModifyJob
/usr/include/KF5/KDAV/DavItemsFetchJob
/usr/include/KF5/KDAV/DavItemsListJob
/usr/include/KF5/KDAV/DavJobBase
/usr/include/KF5/KDAV/DavPrincipalHomesetsFetchJob
/usr/include/KF5/KDAV/DavPrincipalSearchJob
/usr/include/KF5/KDAV/DavUrl
/usr/include/KF5/KDAV/Enums
/usr/include/KF5/KDAV/EtagCache
/usr/include/KF5/KDAV/ProtocolInfo
/usr/include/KF5/kdav/davcollection.h
/usr/include/KF5/kdav/davcollectiondeletejob.h
/usr/include/KF5/kdav/davcollectionmodifyjob.h
/usr/include/KF5/kdav/davcollectionsfetchjob.h
/usr/include/KF5/kdav/davcollectionsmultifetchjob.h
/usr/include/KF5/kdav/daverror.h
/usr/include/KF5/kdav/davitem.h
/usr/include/KF5/kdav/davitemcreatejob.h
/usr/include/KF5/kdav/davitemdeletejob.h
/usr/include/KF5/kdav/davitemfetchjob.h
/usr/include/KF5/kdav/davitemmodifyjob.h
/usr/include/KF5/kdav/davitemsfetchjob.h
/usr/include/KF5/kdav/davitemslistjob.h
/usr/include/KF5/kdav/davjobbase.h
/usr/include/KF5/kdav/davprincipalhomesetsfetchjob.h
/usr/include/KF5/kdav/davprincipalsearchjob.h
/usr/include/KF5/kdav/davurl.h
/usr/include/KF5/kdav/enums.h
/usr/include/KF5/kdav/etagcache.h
/usr/include/KF5/kdav/kdav_export.h
/usr/include/KF5/kdav/protocolinfo.h
/usr/include/KF5/kdav_version.h
/usr/lib64/cmake/KF5DAV/KF5DAVConfig.cmake
/usr/lib64/cmake/KF5DAV/KF5DAVConfigVersion.cmake
/usr/lib64/cmake/KF5DAV/KF5DAVTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5DAV/KF5DAVTargets.cmake
/usr/lib64/libKF5DAV.so
/usr/lib64/qt5/mkspecs/modules/qt_kdav.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5DAV.so.5
/usr/lib64/libKF5DAV.so.5.14.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdav/7e52b139aa82028afadf25f4b534d2404bf97cca
/usr/share/package-licenses/kdav/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files locales -f libkdav.lang
%defattr(-,root,root,-)

